- name: restart ntp
  service: name=ntp state=restarted

- name: restart mysql
  service: name=mysql state=restarted

- name: restart keystone
  service: name=keystone state=restarted

- name: start keystone
  service: name=keystone state=started

- name: restart quantum-server
  service: name=quantum-server state=restarted

- name: restart ovs-agent
  service: name=quantum-plugin-openvswitch-agent state=restarted
  
- name: restart quantum agents
  service: name=$item state=restarted
  with_items:
    - quantum-l3-agent
    - quantum-dhcp-agent
    - quantum-lbaas-agent
    - quantum-metadata-agent
    
- name: restart openvswitch services
  service: name=openvswitch-switch state=restarted

- name: restart web services
  service: name=$item state=restarted
  with_items:
    - apache2
    - memcached