- name: restart ntp
  service: name=ntp state=restarted

- name: restart mysql
  service: name=mysql state=restarted

- name: restart keystone
  service: name=keystone state=restarted

- name: start keystone
  service: name=keystone state=started

- name: restart quantum-server
  service: name=quantum-server state=restarted