- name: ensure horizon packages are installed
  apt: pkg=$item update-cache=yes
  with_items:
    - memcached
    - libapache2-mod-wsgi
    - openstack-dashboard

    # - name: ensure dashboard is configured
    #   copy: >
    #       src=files/etc/openstack-dashboard/local_settings.py
    #       dest=/etc/openstack-dashboard/local_settings.py
    #       owner=root group=root mode=0644 backup=yes
    #   notify: restart services

- name: ensure default virtualhost is disabled
  command: a2dissite default
  notify: restart web services

- name: ensure openstack-dashboard-ssl virtualhost is enabled
  command: a2ensite openstack-dashboard-ssl.conf
  notify: restart web services
  
- name: ensure ssl mod is enabled
  command: a2enmod ssl
  notify: restart web services