- name: stop ntp service
  service: name=ntp state=stopped enabled=no

- name: restart glance-services
  service: name=$item state=restarted
  with_items:
    - glance-registry
    - glance-api

- name: start iSCSI services
  service: name=$item state=started
  with_items:
    - iscsitarget
    - open-iscsi
         
- name: sync cinder db
  command: cinder-manage db sync

- name: restart cinder services
  service: name=$item state=restarted
  with_items:
    - cinder-volume
    - cinder-api
    - cinder-scheduler
