- name: install ntpdate daily cron job
  template: >
    src=etc/cron.daily/ntpdate 
    dest=/etc/cron.daily/ntpdate 
    owner=root group=root mode=0755
  notify: stop ntp service

- include: nova.yml
- include: quantum-plugin-ovs-agent.yml