- name: ensure packages are installed
  apt: pkg=$item
  with_items:
    - openvswitch-common
    - openvswitch-datapath-dkms
    - openvswitch-datapath-source
    - openvswitch-switch
    - kernel-package

- name: ensure OVS kernel module is loaded
  command: /sbin/modprobe openvswitch_mod
  register: modprobe_result
  ignore_errors: True

- name: build openvswitch-datapath kernel module - this may take a while
  command: /usr/bin/module-assistant -i auto-install openvswitch-datapath
  when: modprobe_result|failed
  notify: restart openvswitch services
  
- name: add default ovs bridge br-int for agent
  command: /usr/bin/ovs-vsctl -- --may-exist add-br br-int

- name: install agent package
  apt: name=quantum-plugin-openvswitch-agent

- name: ensure ovs plugin agent configured
  template: >
    src=etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini
    dest=/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini
    owner=quantum group=quantum mode=0660 backup=yes
  notify: restart ovs-agent

- name: ensure quantum.conf is configured
  template: >
    src=etc/quantum/quantum.conf
    dest=/etc/quantum/quantum.conf
    owner=quantum group=quantum mode=0660 backup=yes
  notify: restart ovs-agent