- name: ensure cinder packages are installed
  apt: pkg=$item update_cache=yes
  with_items:
    - cinder-api 
    - cinder-scheduler 
    - cinder-volume 
    - iscsitarget
    - open-iscsi 
    - iscsitarget-dkms 
    - python-cinderclient 
    - linux-headers-3.2.0-4-amd64

- name: ensure iscsitarget is enabled
  lineinfile: >
    dest=/etc/default/iscsitarget
    regexp=^ISCSITARGET_ENABLE
    line=ISCSITARGET_ENABLE=true
  notify:
    - start iSCSI services
      
- name: ensure api-paste.ini is configured
  template: >
    src=etc/cinder/api-paste.ini.j2
    dest=/etc/cinder/api-paste.ini
    owner=cinder group=cinder mode=0640
  notify:
    - restart cinder services

- name: ensure cinder.conf is configured
  template: >
    src=etc/cinder/cinder.conf.j2
    dest=/etc/cinder/cinder.conf
    owner=cinder group=cinder mode=0640
  notify:
    - restart cinder services

- name: ensure vg is created
  lvg: vg=cinder-volumes pvs={{ physical_device }}
  notify: 
    - sync cinder db
    - restart cinder services