- name: ensure sudo is installed
  apt: name=sudo state=present

- name: install ntpdate daily cron job
  template: >
    src=etc/cron.daily/ntpdate 
    dest=/etc/cron.daily/ntpdate 
    owner=root group=root mode=0755
  notify: stop ntp service

- include: glance.yml
- include: cinder.yml